### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/weatherlink2pg#2]
Il faudrait ajouter quelques outils de contrôle de la qualité du code au projet:
- `black`
- `isort`
- `flake8` & `flake8-isort`
- `pylint`
- `pre-commit`

Ce ne sont pas des dépendances de prod, a ajouter au group `dev` qui ne seront pas requis au programme:

```sh
poetry add --group=dev black isort flake8 flake8-isort pylint pre-commit
```
L'ajout de [`pre-commit`](https://pre-commit.com/#intro) pour executer systématiquement ces taches à chaque commit serait aussi pas mal, ça évite d'avoir à y penser et de passer du temps à configurer sont environnement de dev. ça exécute les différents check et reformatage à chaque commit.

On verra plus tard pour des workflow GitHub qui sont très pratiques ;)

**Comment by JohanRocheteau** [comment]
Bonjour,
J'ai ajouté les différent outils et j'ai regardé comment ça marche ne connaissant pas au départ.
J'ai crée le fichier pour faire mon pre-commit mais pour le moment mon code n'est pas très :
- Quelques lignes sont trop longues.
- J'ai tout codé en camelCase (j'ai appris comme ça) mais il me demande de le faire en snake_case.

Tu penses que je lui dis d'omettre ses erreurs ou je modifie et tu me conseils de toujours faire en snake_case?

J'ai déjà utilisé le workflow en formation pour faire les pytests et pour envoyer sur Heroku.

**Comment by JohanRocheteau** [comment]
Bonjour,
J'ai ajouté ces différents outils pour vérifier la qualité du code.
- J'avais tout codé en camelCase ayant appris de cette façon là mais de toute évidence il vaut mieux utiliser le snake_case.
- J'ai cherché un bon moment mais je n'ai pas trouvé d'autres solutions que de mettre une exception sur l'import des librairies, pylint me mettant une erreur à chaque fois.
