### ISSUE TITLE
Factorisation du code

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/weatherlink2pg#3]
La plupart des lignes de code des 3 scripts python sont communs et redondants. Il serait intéressant, maintenant que les fonctionnalités sont bien présentes, d'envisager de créer une appli en ligne de commande (`weatherlink2db` ?) avec 2 options:

- `weatherling2db --full` > Téléchargement complet des données historiques
- `weatherlink2db --update` > Mise à jour des données

@JohanRocheteau, tu peux utiliser [`click`](https://click.palletsprojects.com/en/8.1.x/) qui est une petite lib python qui permet facilement de créer des applis en ligne de commande.

**Comment by JohanRocheteau** [comment]
Oui comme dit sur l'autre issue il y a deux fichiers qui ne servent plus car j'ai voulu tout mettre en un.
A voir ce que tu en penses pour le coup.
Je regarderai la librairie click quand j'aurai validé les modifications sur le reste pour ne pas faire plusieurs fois le même travail.

**Comment by JohanRocheteau** [comment]
Oui c'est redondant car je ne comptais garder que le fichier global.
J'ai supprimé les autres fichiers (.gitignore) et j'ai modifié mon code pour n'avoir que des définitions, j'ai l'impression que pour utiliser "click" c'est le mieux. 
Je regarde tout ça en début de semaine.

**Comment by lpofredc** [comment]
@JohanRocheteau, je viens de créer une petite appli python avec click, si tu veux voir la structuration du projet:
https://github.com/lpoaura/faune-france-global-sensitivity-rules-parser

**Comment by JohanRocheteau** [comment]
@lpofredc Merci j'ai modifié les dossiers en conséquence et j'ai divisé le script en deux avec click d'un coté et les définitions de l'autre comme toi.

**Comment by lpofredc** [comment]
Top, merci. J'ai apporté quelques modifications à la marge sur les scripts:

* Séparation des options `full` et `update` en 2 fonctions distinctes

https://github.com/lpoaura/weatherlink2pg/blob/8e101a32733f97b3e2b632b79cdf520047fbe15c/src/weatherlink2pg/main.py#L40-L67

* Packagé les scripts pour les rendre installables via un simple `pip install weatherlink2pg`

https://github.com/lpoaura/weatherlink2pg/blob/8e101a32733f97b3e2b632b79cdf520047fbe15c/pyproject.toml#L31

https://github.com/lpoaura/weatherlink2pg/blob/8e101a32733f97b3e2b632b79cdf520047fbe15c/pyproject.toml#L34-L35

* Ajout d'une option `--since` pour limiter les téléchargements complets (ça c'était surtout pour me faciliter les tests ;)
* Ajout d'une doc à compléter

https://github.com/lpoaura/weatherlink2pg/tree/main/docs

* Ajout d'actions automatiques GitHub pour:
  * Réaliser quelques tests de qualité de code à chaque nouvelles modifs
  * Générer automatiquement des nouvelles releases à la création de nouveaux "tags"
  * Publier automatiquement la nouvelle version de l'appli à chaque nouvelle release
  * Publier automatiquement la "doc officielle" à chaque nouvelle release

https://github.com/lpoaura/weatherlink2pg/tree/main/.github
